export const WORD_SETS = {
  "1": [
    { en: "a", ja: "a" },
    { en: "s", ja: "s" },
    { en: "d", ja: "d" },
    { en: "f", ja: "f" },
    { en: "g", ja: "g" },
    { en: "h", ja: "h" },
    { en: "j", ja: "j" },
    { en: "k", ja: "k" },
    { en: "l", ja: "l" }
  ],
  "2": [
    { en: "q", ja: "q" },
    { en: "w", ja: "w" },
    { en: "e", ja: "e" },
    { en: "r", ja: "r" },
    { en: "t", ja: "t" },
    { en: "y", ja: "y" },
    { en: "u", ja: "u" },
    { en: "i", ja: "i" },
    { en: "o", ja: "o" },
    { en: "p", ja: "p" }
  ],
  "3": [
    { en: "z", ja: "z" },
    { en: "x", ja: "x" },
    { en: "c", ja: "c" },
    { en: "v", ja: "v" },
    { en: "b", ja: "b" },
    { en: "n", ja: "n" },
    { en: "m", ja: "m" }
  ],
  alphabet: [
    { en: "a", ja: "a" },
    { en: "b", ja: "b" },
    { en: "c", ja: "c" },
    { en: "d", ja: "d" },
    { en: "e", ja: "e" },
    { en: "f", ja: "f" },
    { en: "g", ja: "g" },
    { en: "h", ja: "h" },
    { en: "i", ja: "i" },
    { en: "j", ja: "j" },
    { en: "k", ja: "k" },
    { en: "l", ja: "l" },
    { en: "m", ja: "m" },
    { en: "n", ja: "n" },
    { en: "o", ja: "o" },
    { en: "p", ja: "p" },
    { en: "q", ja: "q" },
    { en: "r", ja: "r" },
    { en: "s", ja: "s" },
    { en: "t", ja: "t" },
    { en: "u", ja: "u" },
    { en: "v", ja: "v" },
    { en: "w", ja: "w" },
    { en: "x", ja: "x" },
    { en: "y", ja: "y" },
    { en: "z", ja: "z" }
  ],
  numbers: [
    { en: "zero", ja: "0" },
    { en: "one", ja: "1" },
    { en: "two", ja: "2" },
    { en: "three", ja: "3" },
    { en: "four", ja: "4" },
    { en: "five", ja: "5" },
    { en: "six", ja: "6" },
    { en: "seven", ja: "7" },
    { en: "eight", ja: "8" },
    { en: "nine", ja: "9" },
    { en: "ten", ja: "10" },
    { en: "eleven", ja: "11" },
    { en: "twelve", ja: "12" },
    { en: "thirteen", ja: "13" },
    { en: "hundred", ja: "100" },
    { en: "thousand", ja: "1000" },
    { en: "million", ja: "1000000" }
  ],
  colors: [
    { en: "red", ja: "赤" },
    { en: "blue", ja: "青" },
    { en: "green", ja: "緑" },
    { en: "yellow", ja: "黄" },
    { en: "black", ja: "黒" },
    { en: "white", ja: "白" },
    { en: "orange", ja: "オレンジ" },
    { en: "purple", ja: "紫" },
    { en: "pink", ja: "ピンク" },
    { en: "brown", ja: "茶色" },
    { en: "gray", ja: "灰色" },
    { en: "gold", ja: "金色" }
  ],
  verbs: [
    { en: "go", ja: "行く" },
    { en: "come", ja: "来る" },
    { en: "eat", ja: "食べる" },
    { en: "drink", ja: "飲む" },
    { en: "see", ja: "見る" },
    { en: "write", ja: "書く" },
    { en: "read", ja: "読む" },
    { en: "sleep", ja: "寝る" },
    { en: "run", ja: "走る" },
    { en: "walk", ja: "歩く" },
    { en: "play", ja: "遊ぶ" },
    { en: "speak", ja: "話す" }
  ],
  fruit: [
    { en: "apple", ja: "りんご" },
    { en: "banana", ja: "バナナ" },
    { en: "cherry", ja: "さくらんぼ" },
    { en: "grape", ja: "ぶどう" },
    { en: "orange", ja: "オレンジ" },
    { en: "peach", ja: "もも" },
    { en: "melon", ja: "メロン" },
    { en: "kiwi", ja: "キウイ" },
    { en: "lemon", ja: "レモン" },
    { en: "mango", ja: "マンゴー" },
    { en: "plum", ja: "すもも" },
    { en: "berry", ja: "ベリー" }
  ],
  conjunctions: [
    { en: "and", ja: "そして" },
    { en: "but", ja: "しかし" },
    { en: "or", ja: "または" },
    { en: "because", ja: "なぜなら" },
    { en: "so", ja: "だから" },
    { en: "although", ja: "〜だけれども" },
    { en: "if", ja: "もし〜なら" },
    { en: "when", ja: "〜するとき" },
    { en: "before", ja: "〜の前に" },
    { en: "after", ja: "〜の後で" },
    { en: "while", ja: "〜している間に" },
    { en: "until", ja: "〜までずっと" }
  ]
};
